### ISSUE TITLE
Docker container stops on boot using latest version of charged

### ISSUE THREAD

**Issue by robertclarkson** [ElementsProject/lightning-charge#79]
Hi my docker compose service looks like this:
```
lightning-charged:
    restart: always
    image: shesek/lightning-charge:0.4.19
    environment:
      NETWORK: mainnet
      API_TOKEN: ${CHARGED_API_TOKEN}
      LN_ALIAS: ${CHARGED_ALIAS}
      LIGHTNINGD_OPT: "--bind-addr=127.0.0.1:9735 --announce-addr=${CHARGED_IP}"
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 9112
      VIRTUAL_HOST: ${CHARGED_HOST}
      # Let's encrypt settings
      # LETSENCRYPT_HOST: ${CHARGED_HOST}
      # LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-yourname@example.com}
      # SKIP_BITCOIND: 1
      BITCOIND_URI: $BITCOIN_URI
      # LN_PATH: /etc/lightning
    volumes:
      - "charged_datadir:/data"
      # - "clightning_bitcoin_datadir:/etc/lightning"
    expose:
      - "9112"
    ports:
      - "9112:9112" # Charge
      - "9735:9735" # Lightning
```

I get the log message 
```
lightning-charged_1  | Connecting to bitcoind at 192.168.10.2:8332... waiting for RPC... ready.
```
But then doesnt load clightning.

if i use container version 0.3.15 then it works but i'm on a super old version of lightning.

Can anyone help?
Thanks
